---
title: "Exploratory Analysis"
output: html_document
---
## Abstract:

Our main question is: how can we find correlations between sleep data and their health outcomes? We chose this question to help identify patterns and factors that may influence the overall health affected by sleep. To address this question, we will analyze a data set that contains sleep data that were provided by users and the contributing factors that influence one's overall health.

## Introduction:

Sleep takes up an enormous portion of our lives, but its effects and importance is widely underestimated and ignored in regards to our health. Current societal standards do not hold sleep to be a crucial necessity to the extent that it should be, as seen by recent statistics. More than a third of Americans are estimated to get less than the recommended 7 hours of sleep, and the percentage of those sleep deprived only get greater when centered around high school and college students, thanks to our culture’s work ethic that promotes productivity over health. Sacrificing sleep in order to get a few more hours of studying, or waking up before the sun rises in order to get to the office– these things are normalized, if not applauded. However, sleep studies have shown that prolonged sleep deprivation can have adverse effects on almost every system in the body, like cardiovascular and nervous systems. Thus, we decided to focus our project on the prevalence of those with health issues and their relationship with sleep in order to detect a significant correlation between the two. Exactly how important is sleep? How does it affect our daily functions? What are the implications of prolonged sleep deprivation? These questions are the motivation behind our research. These questions are important, as they concern the wellbeing of people who may not even know the gravity of losing a few hours of sleep. Further knowledge of the importance of sleep is crucial in order for people to be able to make better informed decisions about their sleep schedules.

## Related Works:

** Extent and Health Consequences of Chronic Sleep Loss and Sleep Disorders**

Institute of Medicine (US) Committee on Sleep Medicine and Research; Colten HR, Altevogt BM, editors. Sleep Disorders and Sleep Deprivation: An Unmet Public Health Problem. Washington (DC): National Academies Press (US); 2006. Available from: https://www.ncbi.nlm.nih.gov/books/NBK19960/ doi: 10.17226/11617

This sleep study recorded sleep loss (which is any nightly sleep that is less than 7 hours) to have effects on cardiovascular, endocrine, immune, and nervous systems. Specifically, they noted obesity, diabetes, cardiovascular disease, hypertension, anxiety, depression, alcoholism to have a strong correlation with individuals who experienced chronic sleep deprivation. Adolescents need 9 hours of sleep, but only 26% get 6.5 hours or less on school nights. Sleep loss only accumulates as they get older.

**What Sleep Loss Does to the Brain and Cognition**

Walton, A. G. (2019, November 29). New Studies Show What Sleep Loss Does To The Brain And Cognition. Forbes. https://www.forbes.com/sites/alicegwalton/2019/11/29/new-studies-show-what-sleep-loss-does-to-the-brain-and-cognition/?sh=3f04e2068e30

A sleep study was conducted on students at Michigan State University. Two groups were created, those who stayed up to work in the labs versus those who got a normal night of sleep. The sleep-deprived group had significantly more lapses in attention compared to the rested group. If prolonged, chronic sleep deprived individuals more at risk for cognitive decline, like Alzheimer’s.

**Causes and consequences of sleepiness among college students**

Wang, Z., & Zhao, H. (2014). Sleep deprivation: Impact on cognitive performance. Neuropsychiatric Disease and Treatment, 10, 1809–1825. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4075951/

This article focuses on daytime sleepiness, sleep deprivation’s impact on college students’ academic performance and health. Factors contributing to sleep deprivation (irregular sleep schedules, academic workload, phone/technology use, social factors; including parties, social gatherings.., stress and anxiety, environmental factors; noise, light pollution, dorm, temperature). Some correlations found between sleep and learning included memory consolidation, acquisition of knowledge, attention, concentration, and emotional regulation.

## Datasets:

**Sleep health and lifestyle dataset**

We used the "Sleep Health and Lifestyle Dataset" from Kaggle as our dataset. The data was accumulated from the University of Michigan records, which was compiled on sleep customs, health behaviors, and lifestyle habits. Through a restricted number of methods such as inquiry and questionnaire, people are finding the relationship between the sleep health and life domains. The target of data-gathering is to gain knowledge about the subject's sleep habits, routine, and present state of health. For ethical reasons, the approach to information management would have to be deliberate. Compared to this, we have to ensure the participant’s confidentiality and have their data being utilized properly and responsibly without any ethical concerns in the interpretation. On the other hand, there is self-report bias in this research, so participants may not be able to correctly report their sleep patterns and health behaviors.

**Total Sleep Deprivation Increases Brain Age Prediction Reversibly in Multisite Samples of Young Healthy Adults**

“Sleep Deprivation among College Students in the US '' was the focus of the study conducted by the National Center for Biotechnology Information (NCBI). Survey, interview, and some objective measurement like sleep tracker are used to gather statistics and research findings on sleep deprivation among college students in the U.S. The aim of the reaserch was to identify the prevalence, causes, and consequences of sleep deprivation among college students having in consideration the fact of academic workload, lifestyle, and mental health. This dataset also needs to address ethical issues. Given the study that involves an individual's academic work, personal life, and mental health, we should be careful that stigmatization or discrimination does not occur. One of these drawbacks is self-reporting biases and the fact that many complex factors can interfere with sleep.

**Effect of 24-hour sleep deprivation on cerebral hemodynamics and cognitive performance**

The University of Oklahoma was the data collection site and it examined how sleep deprivation would affect cerebrovascular hemodynamics in young adults. The study consisted of ten healthy adult males (Mean age of 27.6) with pre and post fNIRS measurement. The participants had performed different cognitive tests before and after the 24-hour total sleep deprivation. The dataset covers the effect that it has on the decision process. The data will thereby assist us in knowing how sleep deficiency affects cognitive functioning and general brain health in general. This data will be supervised by monitoring participants' hemodynamic parameters (heart rate, blood pressure) and cognitive performance (reaction times, memory tests) during the stages of sleep deprivation. The drawback is that the sleep deprivation conditions may not mimic the work patterns and behaviors exactly.

## Implications

Our research regarding correlations between sleep and health effects could lead to a better understanding of the long term health implications of sleep deprivation. Because our current work culture encourages productivity to the extent of staying up late and waking up early, it is extremely important to better educate individuals about the exact effects of doing such things so that they are aware of the consequences of chronic sleep deprivation. A lot of people are not acutely aware of just how big of a factor sleep is, so our research would encourage more widespread awareness. Thus, having a better understanding of sleep could help people prioritize and find a healthier balance between work and rest. In addition to this, our research could find existing correlations between sleep and other health factors, which would specify the exact kinds of effects that sleep deprivation could have on an individual. Future societal implications could include a new school system, one that allows students to sleep in, or more mandated education regarding sleep.

## Limitations and Challenges

One of the challenges that we may face is the reliability of sleep data that is collected. Sleep tracking technology may lack accuracy and factors such as movement during sleep or certain environmental conditions may affect the data’s quality. Addressing this challenge will involve putting together robust algorithms and validation processes to filter and have the tracking system interpret data more effectively. 

Privacy and data security is a challenge we need to overcome as there are many concerns surrounding digital health applications. It is important to ensure that user data is protected and will be in compliance with relevant privacy regulations to be able to build trust among users and secure sensitive information. 

Being able to address the diverse needs and preferences in regards to recommending ways to improve sleep habits is crucial. Some resources that work for an individual may not work for another. So the platform must stay flexible and adaptable to accommodate the wide range of users and their unique circumstances. 

Addressing these challenges requires technological innovation, user engagement strategies, privacy measures, and the deep understanding of sleep health in order to create a successful web application. 

Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

```{r, echo = FALSE, code = readLines("chart1_example.R")}

Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
